# Generated by Django 5.2.14 on 2026-06-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('exploitable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('OCCUPE', 'Occupé'), ('INEXPLOITABLE', 'Inexploitable')], default='DISPONIBLE', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('longueur', models.FloatField(default=2.0)),
                ('largeur', models.FloatField(default=1.0)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='terrain.bloc')),
            ],
        ),
        migrations.AddField(
            model_name='bloc',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs', to='terrain.zone'),
        ),
    ]
