# Generated by Django 5.2.14 on 2026-06-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_concession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture')),
            ],
        ),
    ]
