# Generated by Django 5.2.14 on 2026-06-03 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('nom_defunt', models.CharField(max_length=100)),
                ('prenom_defunt', models.CharField(max_length=100)),
                ('date_deces', models.DateField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='terrain.caveau')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
